
name: pullrequest

on:
  pull_request:
    branches: 
    - 'master'

jobs:
  pr:
    name: Pull Request Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
      - name: Terraform Validate Dev
        run: |
          cd infra/dummy-app/development
          terraform init
          terraform validate
          cd ../
      - name: Terraform Validate PROD
        run: |
          cd infra/dummy-app/production
          terraform init
          terraform validate